[package]
name = "dua-cli"
version = "0.1.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
failure = "0.1.1"
failure-tools = "4.0.2"
structopt = "0.2.14"
jwalk = "0.4.0"
byte-unit = "2.1.0"

[[bin]]
name="dua"
path="src/main.rs"

[lib]
name="dua"

[profile.release]
panic = 'unwind'
incremental = false
overflow-checks = false
